### ISSUE TITLE
加入靈基素材需求？

### ISSUE THREAD

**Issue by eight04** [tsukimiyamiyabi/tsukimiyamiyabi.github.io#1]
如果 @tsukimiyamiyabi 沒空的話，我可以幫忙寫靈基素材的部份。不知道意下如何？資料是從 wiki 複製再手動寫進 data.js 裡的嗎？

可能還會有些小修正︰
* min skill 設為「請選擇」時 max skill 會多出一個「0」的項目
* 變更育成英靈數時不要將整個列表重設
* 素材 <=> 英靈的雙向跳轉
	- 在英靈頁面點選素材時，自動跳到素材頁並選擇該素材
	- 在素材頁面點選英靈時，自動跳到英靈頁並將該英靈加入列表

**Comment by tsukimiyamiyabi** [comment]
OKOK ,太感謝了
小更新還OK，不過大更新就沒什麼時間了 (--不會說只是懶而已--)
資料是從wiki 複製，然後用我另外寫的C去轉成JS，一個一個手動填有點累QQ

**Comment by eight04** [comment]
https://www9.atwiki.jp/f_go/pages/302.html
https://www9.atwiki.jp/f_go/pages/160.html
是這兩頁嗎？

**Comment by tsukimiyamiyabi** [comment]
對，我技能的部分主要是參考上面那個連結，
下面靈基的部分因為沒做，所以沒用到

**Comment by eight04** [comment]
分支位址︰
https://github.com/eight04/tsukimiyamiyabi.github.io/tree/dev-ascension

預覽︰
https://rawgit.com/eight04/tsukimiyamiyabi.github.io/dev-ascension/fgo-skillitem/index.html

目前進度︰
- [x] 加入靈基材料的 data
- [x] 介面控制
- [x] 把資料整合進加總的表格中
- [ ] 加入金棋和銀棋的圖片

我看不懂 ttData 是如何運作的。要如何在使用者指定完靈基等級後把材料數量加上去呢？

**Comment by tsukimiyamiyabi** [comment]
哦哦，我的ttData的結構是一個二維陣列=> ttData[育成英靈數量*3+1][素材種類數量+1]

ttData[0][0-47(目前素材47種) ] 這組是存放總和，[0][0]是QP，[0][1]是劍之輝石總和，以此類推。
ttData[育成英靈數量 * 0 + n][0-47]，1<= n <=育成英靈數量, 為第n個育成英靈的第1組素材存放空間，
ttData[育成英靈數量 * 1 + n][0-47]，1<= n <=育成英靈數量, 為第n個育成英靈的第2組素材存放空間，
ttData[育成英靈數量 * 2 + n ][0-47],  1<= n <=育成英靈數量, 為第n個育成英靈的第3組素材存放空間。
假設育成英靈數量為3，
則ttData[1,4,7][] 為英靈1的第1,2,3組，ttData[2,5,8][]為英靈2的第1,2,3組， ttData[3,6,9][]為英靈2的第1,2,3組。

英靈編號選單 or 最大技能等級選單變動時，會用ttDataClear()把有變動的那組清空，然後在myTable()繪製表格的時候會同時把數量填進去，最後在呼叫myTable2()繪製總和表格之前會先透過countItemAll()計算總合。

**Comment by eight04** [comment]
素材圖示好像不是來自 https://kazemai.github.io/fgo-vz/item_drop.html？

**Comment by tsukimiyamiyabi** [comment]
素材圖示是我自己拍圖裁切的

**Comment by eight04** [comment]
這就沒辦法了，我只有玩中國版，有好多不認識的材料
```
	"ゴーストランタン": 62,
	"ホムンクルスベビー": 63,
	"ティンクルキャンディ": 64,
	"黄金髑髏": 65,
	"樽入りチキン": 66,
	"業物ナイフ": 67,
	"水晶球": 68,
	"ゴールデンベアライター": 69,
	"鈴鳴りの枝": 70,
	"ハートのブレスレット": 71,
	"竜のオーブ": 72
```

**Comment by tsukimiyamiyabi** [comment]
就用茹西主教的圖吧QQ
畢竟我這邊素材用掉了也沒東西可以拍了

**Comment by eight04** [comment]
這個表裡好像有重覆的東西……
https://github.com/eight04/tsukimiyamiyabi.github.io/blob/dev-ascension/fgo-skillitem/data-item.js
```
"ｺﾞｰｽﾄﾗﾝﾀﾝ" == "ゴーストランタン"
"ﾎﾑﾝｸﾙｽﾍﾞﾋﾞｰ" == "ホムンクルスベビー"
```

**Comment by tsukimiyamiyabi** [comment]
摁，重複的O_o
不過這表不是你做的嗎@@?

**Comment by eight04** [comment]
我直接從 https://www9.atwiki.jp/f_go/pages/160.html 複製
還真的跟 https://www9.atwiki.jp/f_go/pages/302.html 上的文字不太一樣

**Comment by tsukimiyamiyabi** [comment]
同樣的道具，全形半形差別而已，可能是為了排版??
我是從302複製，所以是用半形字
